server:
  port: 8080

spring:
  application:
      name: spring_security_basic_authentication
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_general_ci
    username: root
    password: test123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        use-new-id-generator-mappings: false
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    open-in-view: false
