spring:

  #Error Responses Handler Configuration
  mvc:
    throw-exception-when-servlet-resource-not-found: true

  #Datasource Configuration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: MainHikariPool
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000

  #JPA Configuration
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: disable
        format_sql: true
        connection:
          pool_size: 30
        order_updates: true

#Logging Configuration
logging:
  level:
    root: INFO
    com.zaxxer.hikari: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: INFO

#Server Configuration
server:
  port: 8181

#Jwt Configuration
jwt:
  secret-key: ${SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
